#configuracion de resilience4j 
resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6 #número de pruebas en estado de prueba
        failure-rate-threshold: 50 #porcentaje de error 
        wait-duration-in-open-state: 20s #tiempo de espera en estado abierto
        permitted-number-of-calls-in-half-open-state: 4 #máximo de llamadas en estado semi-abierto
        slow-call-rate-threshold: 50 #porcentaje de umbral de llamadas lentas
        slow-call-duration-threshold: 2s #tiempo para considerar la request como llamada lenta
    instances:
      items:
        base-config: defecto #añadimos la configuracion de "defecto" a las instancias. En este caso a "items"
  timelimiter:
    configs:
      defecto:
        timeout-duration: 2s #tiempo antes de lanzar un timeOutException
    instances:
      items:
        base-config: defecto #añadimos configuracion defecto del time limiter